iconpack:
  title: "Flag Icons"
  key: "flagicons"
  version: 1.5.19
  url: "https://gitlab.com/catamphetamine/country-flag-icons/"

  renderTypes:

    _default:
      prefix: "flagicons flagicons-"

    webfont:
      css: "EXT:iconpack_flagicons/Resources/Public/Vendor/iconfont/flagicons.css"

    svg:
      source: "EXT:iconpack_flagicons/Resources/Public/Vendor/svgs/"

    svgInline:
      source: "EXT:iconpack_flagicons/Resources/Public/Vendor/svgs/"
      attributes:
        fill: "currentColor"

  icons: "EXT:iconpack_flagicons/Resources/Public/Vendor/metadata/icons.yml"
